# Generated by Django 3.0.5 on 2020-04-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(default='Private', max_length=30),
            preserve_default=False,
        ),
    ]
